# Build and Test Application

name: Build and Test

on:
  workflow_call:

inputs:
  os:
    description: 'The os to test on'
    required: true
    default: 'ubuntu-latest'
  node-v:
    description: 'The node version'
    required: true
    default: '16.x'
  workdir:
    description: 'The working directory'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      working-directory: ${{ inputs.workdir }}
      run: npm ci
    - name: Building ${{ inputs.workdir }} App
      working-directory: ${{ inputs.workdir }}
      run: npm run build --if-present
    - name: Testing ${{ inputs.workdir }} App
      working-directory: ${{ inputs.workdir }}
      run: npm test
# jobs:
#   perform-build:
#     name: Build and Test application
#     runs-on: ${{ inputs.os }}
#     steps:
        