# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

name: Application Build
description: Checks for the proper build and test functionality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ${{matrix.os}}
    environment: production
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ./.github/workflows/build-and-test
        with:
          os: ${{matrix.os}}
          node-v: ${{matrix.node-version}}
          workdir: 'server'
  build-frontend:
    runs-on: ${{matrix.os}}
    environment: production
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ./.github/workflows/build-and-test
        with:
          os: ${{matrix.os}}
          node-v: ${{matrix.node-version}}
          workdir: 'client'