# Checks for the proper build and test functionality

name: Application Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ${{matrix.os}}
    environment: production
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ./.github/workflows/build-and-test
        with:
          os: ${{matrix.os}}
          node-v: ${{matrix.node-version}}
          workdir: 'server'
  build-frontend:
    runs-on: ${{matrix.os}}
    environment: production
    strategy:
      matrix:
        node-version:
          - 16.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: ./.github/workflows/build-and-test
        with:
          os: ${{matrix.os}}
          node-v: ${{matrix.node-version}}
          workdir: 'client'